test = {   'name': 'q1_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> election.num_rows == 53\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> election.num_columns == 66\nTrue', 'hidden': False, 'locked': False},
                                   {'code': ">>> max(list(election.labels)) == 'Unnamed: 60'\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> min(list(election.labels)) == '1789'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
