test = {   'name': 'q2_3',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> classify_knn(lobster, make_array(17,5), 1)\n1', 'hidden': False, 'locked': False},
                                   {'code': '>>> classify_knn(lobster, make_array(10,5), 3)\n0', 'hidden': False, 'locked': False},
                                   {'code': '>>> classify_knn(lobster, make_array(10,18), 1)\n1', 'hidden': False, 'locked': False},
                                   {'code': '>>> classify_knn(lobster, make_array(10,18), 3)\n0', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
